### ISSUE TITLE
Not too much practice

### ISSUE THREAD

**Issue by jmulloy** [learn-co-curriculum/js-dom-and-events-intro-to-the-dom-code-along#5]
When I cloned and forked I noticed most of the changes requested to be made in the code along were already done. Also, everytime I hit refresh the httpserver that kept the link live would end and the server wouldnt be connected. Not sure how to fix this.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so that the readme and files correctly align and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
